### ISSUE TITLE
[feat] - 새 todo등록, 등록된 todo 목록을 feed에 불러오기

### ISSUE THREAD

**Issue by kewii33** [wonjangnimsamgyetang-team3/followingfollower#14]
📕 Issue Feature 
새 todo등록, 등록된 todo 목록을 feed에 불러오기

🧾Todo
- [ ] 새 todo등록
- 제목, 내용 입력, 이미지는 업로드할 수 있으나 아직 데이터 베이스에 저장 불가.
- title value에 타입이 안맞는 오류가 있으나 기능은 정상적으로 작동함.
- /components/NewTodo.tsx
`'use client';

import Image from 'next/image';
import React, { ChangeEvent, FormEvent, useState } from 'react';
import { FaPhotoVideo } from 'react-icons/fa';
import { createClient } from '@supabase/supabase-js';
import { Database } from 'database.types';
import { useRouter } from 'next/navigation';

const NewTodo= () => {
  const [dragging, setDragging] = useState(false);
  const [file, setFile] = useState<File>();
  const router = useRouter();

  //이미지 파일 업로드, 드랍
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    const files = e.target?.files;
    if (files && files[0]) {
      setFile(files[0]);
    }
  };
  const handleDrag = (e: React.DragEvent) => {
    if (e.type === 'dragenter') {
      setDragging(true);
    } else if (e.type === 'dragleave') {
      setDragging(false);
    }
  };
  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
  };
  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragging(false);
    const files = e.dataTransfer?.files;
    if (files && files[0]) {
      setFile(files[0]);
    }
  };

  //supabase에 todo 저장
  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!file) return;

    const formData = new FormData();
    //'value' 속성이 'string' 형식에 없습니다. 'valueOf'을(를) 사용하시겠습니까?라는 오류가 나는데 뭐가 문제인지 잘 모르겠음.
    formData.append('title', e.currentTarget['title'].value);
    formData.append('contents', e.currentTarget['contents'].value);
    formData.append('start', e.currentTarget['start'].value);
    formData.append('end', e.currentTarget['end'].value);
    formData.append('file', file);

    const todoData = {
      title: formData.get('title') as string,
      contents: formData.get('contents') as string,
      start: formData.get('start') as string,
      end: formData.get('end') as string,
    };

    const { data } = await supabase.from('TodoList').insert([todoData]);

    alert('등록 완료!');
    router.push('/feed');
  };

  const supabase = createClient<Database>(
    'https://jcsjtjiqolsewkoutsag.supabase.co',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjc2p0amlxb2xzZXdrb3V0c2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA4MzEyOTMsImV4cCI6MjAyNjQwNzI5M30.Mm1I1g_5qrNONvPK8gsK_3xDBim04lX01cQAX1yXVB0'
  );

  return (
    <div className="w-full h-full flex flex-col flex items-center flex justify-center bg-[#e3e3e3]">
      <section className="w-[700px] h-[900px] outline-none flex flex-col items-center justify-center mt-20 mb-20 bg-white border-2 border-[#fb8494] rounded-[30px] p-[40px]">
        <div className="text-lg text-[#fb8494] mb-[20px]">username</div>
        <form className="w-full flex flex-col mt-2" onSubmit={handleSubmit}>
          <textarea
            className="w-15 h-12 outline-none text-lg border-2 border-[#fb8494] rounded-[30px] resize-none p-[8px] pl-[15px]"
            name="title"
            id="input-title"
            required
            rows={1}
            placeholder="제목을 입력하세요."
          />
          <div className="mt-[30px] mb-[30px]">
            <input
              className="hidden flex items-center flex justify-center"
              name="input"
              id="input-upload"
              type="file"
              accept="image/*"
              onChange={handleChange}
            />
            <label
              className={`w-full h-60 flex flex-col items-center justify-center rounded-[20px] ${
                !file && 'border-2 rounded-[20px] border-gray-500 border-dashed'
              }`}
              htmlFor="input-upload"
              onDragEnter={handleDrag}
              onDragLeave={handleDrag}
              onDragOver={handleDragOver}
              onDrop={handleDrop}
            >
              {dragging && (
                <div className="absolute inset-0 z-10 bg-sky-500/20 pointer-events-none" />
              )}
              {!file && (
                <div className="flex flex-col items-center pointer-events-none">
                  <FaPhotoVideo className="w-20 h-20 text-gray-300 mb-[10px]" />
                  <p>클릭하여 이미지를 등록해주세요.</p>
                </div>
              )}
              {file && (
                <div className="relative w-full aspect-square">
                  <Image
                    className="object-cover"
                    src={URL.createObjectURL(file)}
                    alt="local file"
                    fill
                    sizes="650px"
                  />
                </div>
              )}
            </label>
          </div>
          <textarea
            className="h-[250px] outline-none text-lg resize-none border-2 border-[#fb8494] rounded-[30px] p-[15px] bg-[#ececec]"
            name="contents"
            id="input-contents"
            required
            rows={10}
            placeholder="할 일 자세히 입력( 100글자 이내 )"
          />
          <div className="flex p-[10px] mt-[20px]">
            <div className="mr-[30px]">
              <label className="mr-[10px] text-[#fb8494]" htmlFor="start">
                시작일
              </label>
              <input
                id="start"
                type="date"
                name="start"
                min="1800-01-01"
                max="2200-12-31"
              />
            </div>
            <div className="">
              <label className="mr-[10px] text-[#fb8494]" htmlFor="end">
                마감일
              </label>
              <input
                id="end"
                type="date"
                name="end"
                min="1800-01-01"
                max="2200-12-31"
              />
            </div>
          </div>
          <button className="h-[50px] bg-[#fb8494] rounded-[15px] text-white font-bold mt-[30px]">
            할 일 등록
          </button>
        </form>
      </section>
    </div>
  );
};

export default NewTodo;
`

- [ ] 등록된 todo 목록을 feed에 불러오기
- setTodoData(data) 타입 오류가 있으나 기능은 정상적으로 작동함.
- TodoCard.tsx와 TodoList.tsx사용
- /components/TodoList.tsx
`
'use client';

import React, { useEffect, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { Database } from '../../database.types';
import TodoCard from './TodoCard';

const supabase = createClient<Database>(
  'https://jcsjtjiqolsewkoutsag.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjc2p0amlxb2xzZXdrb3V0c2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA4MzEyOTMsImV4cCI6MjAyNjQwNzI5M30.Mm1I1g_5qrNONvPK8gsK_3xDBim04lX01cQAX1yXVB0'
);

interface TodoData {
  contents: string;
  created_at: string;
  end: string;
  file: string;
  likeCount: number;
  liked: boolean;
  nickname: string;
  start: string;
  title: string;
  todoId: string;
}

const TodoList = () => {
  const [todoData, setTodoData] = useState<TodoData[]>([]);

  useEffect(() => {
    getTestData();
  }, []);

  async function getTestData() {
    let { data } = await supabase.from('TodoList').select('*');
    setTodoData(data);
  }

  return (
    <div className="grid grid-cols-3 mb-[30px] bg-sky-500 mt-[50px]">
      {todoData.map((item, index) => (
        <TodoCard key={index} todo={item} />
      ))}
    </div>
  );
};

export default TodoList;
`

- /components/TodoCard.tsx
`'use client';

import React, { useState, useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';
import { Database } from 'database.types';
import ToggleButton from './ToggleButton';
import HeartFillIcon from '../icons/HeartFillIcon';
import { HeartIcon } from '@/icons/HeartIcon';

const supabase = createClient<Database>(
  'https://jcsjtjiqolsewkoutsag.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjc2p0amlxb2xzZXdrb3V0c2FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTA4MzEyOTMsImV4cCI6MjAyNjQwNzI5M30.Mm1I1g_5qrNONvPK8gsK_3xDBim04lX01cQAX1yXVB0'
);

interface TestData {
  contents: string;
  created_at: string;
  end: string;
  file: string;
  likeCount: number;
  liked: boolean;
  nickname: string;
  start: string;
  title: string;
  todoId: string;
}

interface TodoType {
  contents: string;
  created_at: string;
  end: string;
  file: string;
  likeCount: number;
  liked: boolean;
  nickname: string;
  start: string;
  title: string;
  todoId: string;
}

const TodoCard = ({ todo }: { todo: TodoType }) => {
  const [liked, setLiked] = useState(false);
  const [testData, setTestData] = useState<TestData[]>([]);

  if (!todo) {
    return <div>데이터 없음</div>;
  }

  const { title, nickname, contents, created_at } = todo;

  const formattedDate = new Date(created_at).toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });

  return (
    <div className="bg-white m-[15px]">
      <h2>{title}</h2>
      <p>{nickname}</p>
      <p>{contents}</p>
      <p>{formattedDate}</p>
      <div>
        <ToggleButton
          toggled={liked}
          onToggle={setLiked}
          onIcon={<HeartFillIcon />}
          offIcon={<HeartIcon />}
        />
      </div>
    </div>
  );
};

export default TodoCard;
`

- [ ] 토글 버튼 로직 추가
- 토글 버튼을 사용하여 하트를 눌렀을 때 빈 하트에서 채워진 하트로 변경되는 것처럼 다른 아이콘에도 on/off를 할 수 있도록 ToggleButton.tsx파일을 추가함.
- ToggleButton.tsx
`import React from 'react';

type Props = {
  toggled: boolean;
  onToggle: (toggled: boolean) => void;
  onIcon: React.ReactNode;
  offIcon: React.ReactNode;
};

const ToggleButton = ({ toggled, onToggle, onIcon, offIcon }: Props) => {
  return (
    <div>
      <button onClick={() => onToggle(!toggled)}>
        {toggled ? onIcon : offIcon}
      </button>
    </div>
  );
};

export default ToggleButton;`

- ToggleButton 사용 예시
`
  const [liked, setLiked] = useState(false);
<div>
        <ToggleButton
          toggled={liked}
          onToggle={setLiked}
          onIcon={<HeartFillIcon />}
          offIcon={<HeartIcon />}
        />
      </div>
`
ToggleButton을 import해 온 뒤 onIcon일 때 HeartFillIcon, offIcon일 때 HeartIcon을 사용하여 클릭 전에는 빈 하트, 클릭 후에는 채워진 하트로 보이게 함.

- [ ]  icons 폴더 및 하트 아이콘 파일 추가
- icons/HeartIcon.tsx
`
import { AiOutlineHeart } from 'react-icons/ai';

type Props = {
  className?: string;
};

export const HeartIcon = ({ className }: Props) => {
  return (
    <AiOutlineHeart
      className={className || 'w-7 h-7'}
      style={{ color: 'red' }}
    />
  );
};

`
- icons/HeartFillIcon.tsx
`import React from 'react';
import { AiFillHeart } from 'react-icons/ai';

const HeartFillIcon = () => {
  return (
    <div>
      <AiFillHeart style={{ color: 'red' }} />
    </div>
  );
};

export default HeartFillIcon;
`
